// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKKcD-cplstNaRPM4eTeKMTWAel5sbLw8',
    appId: '1:814128476971:web:1a13d07729593f801d4b6e',
    messagingSenderId: '814128476971',
    projectId: 'your-money-de3b4',
    authDomain: 'your-money-de3b4.firebaseapp.com',
    storageBucket: 'your-money-de3b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNNm-tExg10uH40w3C1QBv6YtIPjIMrBI',
    appId: '1:814128476971:android:7eb4f6a1654f4c9a1d4b6e',
    messagingSenderId: '814128476971',
    projectId: 'your-money-de3b4',
    storageBucket: 'your-money-de3b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHm6cqWeTTjmhQe4ixHve9P2vX4HBj1Gk',
    appId: '1:814128476971:ios:726a0baf6e9d13711d4b6e',
    messagingSenderId: '814128476971',
    projectId: 'your-money-de3b4',
    storageBucket: 'your-money-de3b4.appspot.com',
    iosBundleId: 'com.example.yourMoneyFlutter',
  );
}
